-- DoTimer_SpellLocalization.lua
-- Sistema de traducción español→inglés para DoTimer
-- Versión: 1.0
-- Fecha: Enero 9, 2026

DoTimer_SpellLocalization = {}

-- Detectar idioma del cliente
local locale = GetLocale()

if locale == "esES" or locale == "esMX" then
    -- WARLOCK
    DoTimer_SpellLocalization["Maldición de las Lenguas"] = "Curse of Tongues"
    DoTimer_SpellLocalization["Corrupción"] = "Corruption"
    DoTimer_SpellLocalization["Inmolar"] = "Immolate"
    DoTimer_SpellLocalization["Inferno"] = "Inferno"
    DoTimer_SpellLocalization["Lengua de Muerte"] = "Death Coil"
    DoTimer_SpellLocalization["Maldición de la Perdición"] = "Curse of Doom"
    DoTimer_SpellLocalization["Esclavizar Demonio"] = "Enslave Demon"
    DoTimer_SpellLocalization["Seducción"] = "Seduction"
    DoTimer_SpellLocalization["Seducir"] = "Seduction"
    DoTimer_SpellLocalization["Maldición de Agonía"] = "Curse of Agony"
    DoTimer_SpellLocalization["Maldición de Debilidad"] = "Curse of Weakness"
    DoTimer_SpellLocalization["Maldición de Imprudencia"] = "Curse of Recklessness"
    DoTimer_SpellLocalization["Maldición de las Sombras"] = "Curse of Shadow"
    DoTimer_SpellLocalization["Desterrar"] = "Banish"
    DoTimer_SpellLocalization["Maldición de los Elementos"] = "Curse of the Elements"
    DoTimer_SpellLocalization["Hechizo de Paranoia"] = "Spell Lock"
    DoTimer_SpellLocalization["Miedo"] = "Fear"
    DoTimer_SpellLocalization["Aullido de Muerte"] = "Howl of Terror"
    DoTimer_SpellLocalization["Conflagración"] = "Conflagrate"
    DoTimer_SpellLocalization["Sifón de Vida"] = "Siphon Life"
    DoTimer_SpellLocalization["Maldición de Agotamiento"] = "Curse of Exhaustion"
    DoTimer_SpellLocalization["Quemadura de las Sombras"] = "Shadowburn"
    DoTimer_SpellLocalization["Transfusión de Vida"] = "Life Tap"
    DoTimer_SpellLocalization["Vulnerabilidad a las Sombras"] = "Shadow Vulnerability"
    DoTimer_SpellLocalization["Invocar Xorothian"] = "Summon Xorothian"
    DoTimer_SpellLocalization["Invocar Súcubo"] = "Summon Succubus"
    DoTimer_SpellLocalization["Invocar Abisario"] = "Summon Voidwalker"
    DoTimer_SpellLocalization["Invocar Diablillo"] = "Summon Imp"
    DoTimer_SpellLocalization["Invocar Manáfago"] = "Summon Felhunter"
    DoTimer_SpellLocalization["Invocar Guardia Vil"] = "Summon Felguard"
    DoTimer_SpellLocalization["Ojo de Kilrogg"] = "Eye of Kilrogg"
    DoTimer_SpellLocalization["Crear Piedra Demoníaca"] = "Create Spellstone"
    DoTimer_SpellLocalization["Crear Piedra Demoníaca Inferior"] = "Create Spellstone (Lesser)"
    DoTimer_SpellLocalization["Crear Piedra Demoníaca Menor"] = "Create Spellstone (Minor)"
    DoTimer_SpellLocalization["Crear Piedra Demoníaca Sublime"] = "Create Spellstone (Major)"
    DoTimer_SpellLocalization["Crear Piedra Demoníaca Superior"] = "Create Spellstone (Greater)"
    DoTimer_SpellLocalization["Ritual de Invocación"] = "Ritual of Summoning"
    DoTimer_SpellLocalization["Resguardo Contra las Sombras"] = "Shadow Ward"
    DoTimer_SpellLocalization["Descarga de las Sombras"] = "Shadow Bolt"
    DoTimer_SpellLocalization["Dolor Abrasador"] = "Searing Pain"
    DoTimer_SpellLocalization["Fuego de Alma"] = "Soul Fire"
    DoTimer_SpellLocalization["Llamas Infernales"] = "Hellfire"
    DoTimer_SpellLocalization["Lluvia de Fuego"] = "Rain of Fire"
    
    -- PRIEST
    DoTimer_SpellLocalization["Grilletes de los Muertos"] = "Shackle Undead"
    DoTimer_SpellLocalization["Calmar Mente"] = "Mind Soothe"
    DoTimer_SpellLocalization["Abolir Enfermedad"] = "Abolish Disease"
    DoTimer_SpellLocalization["Palabra de las Sombras: Dolor"] = "Shadow Word: Pain"
    DoTimer_SpellLocalization["Grito Psíquico"] = "Psychic Scream"
    DoTimer_SpellLocalization["Peste Devoradora"] = "Devouring Plague"
    DoTimer_SpellLocalization["Renovar"] = "Renew"
    DoTimer_SpellLocalization["Palabra de Poder: Escudo"] = "Power Word: Shield"
    DoTimer_SpellLocalization["Maleficio de Debilidad"] = "Hex of Weakness"
    DoTimer_SpellLocalization["Toque Vampírico"] = "Vampiric Touch"
    DoTimer_SpellLocalization["Abrazo Vampírico"] = "Vampiric Embrace"
    DoTimer_SpellLocalization["Supresión de Magia"] = "Magic Suppression"
    DoTimer_SpellLocalization["Silencio"] = "Silence"
    DoTimer_SpellLocalization["Control Mental"] = "Mind Control"
    DoTimer_SpellLocalization["Levitación"] = "Levitate"
    DoTimer_SpellLocalization["Temor"] = "Fear Ward"
    DoTimer_SpellLocalization["Protección contra el Miedo"] = "Fear Ward"
    DoTimer_SpellLocalization["Debilitar Alma"] = "Weakened Soul"
    DoTimer_SpellLocalization["Oración de Curación"] = "Prayer of Healing"
    DoTimer_SpellLocalization["Curación Veloz"] = "Flash Heal"
    DoTimer_SpellLocalization["Curación Superior"] = "Greater Heal"
    
    -- WARRIOR
    DoTimer_SpellLocalization["Lacerar"] = "Rend"
    DoTimer_SpellLocalization["Hender Armadura"] = "Sunder Armor"
    DoTimer_SpellLocalization["Grito Desmoralizador"] = "Demoralizing Shout"
    DoTimer_SpellLocalization["Atronar"] = "Thunder Clap"
    DoTimer_SpellLocalization["Provocar"] = "Taunt"
    DoTimer_SpellLocalization["Cortar Tendón"] = "Hamstring"
    DoTimer_SpellLocalization["Desarmar"] = "Disarm"
    DoTimer_SpellLocalization["Aullido Perforante"] = "Piercing Howl"
    DoTimer_SpellLocalization["Grito Intimidador"] = "Intimidating Shout"
    DoTimer_SpellLocalization["Golpe Mortal"] = "Mortal Strike"
    
    -- PALADIN
    DoTimer_SpellLocalization["Sentencia de Sabiduría"] = "Judgement of Wisdom"
    DoTimer_SpellLocalization["Sentencia de Luz"] = "Judgement of Light"
    DoTimer_SpellLocalization["Expulsar No-muerto"] = "Turn Undead"
    DoTimer_SpellLocalization["Martillo de Justicia"] = "Hammer of Justice"
    DoTimer_SpellLocalization["Sentencia del Cruzado"] = "Judgement of the Crusader"
    DoTimer_SpellLocalization["Arrepentimiento"] = "Repentance"
    
    -- DRUID
    DoTimer_SpellLocalization["Lacerar"] = "Rake"
    DoTimer_SpellLocalization["Desgarrar"] = "Rip"
    DoTimer_SpellLocalization["Mordedura Feroz"] = "Ferocious Bite"
    DoTimer_SpellLocalization["Zarpazo"] = "Claw"
    DoTimer_SpellLocalization["Destrozar"] = "Shred"
    DoTimer_SpellLocalization["Golpe con Mazo"] = "Maul"
    DoTimer_SpellLocalization["Vapulear"] = "Bash"
    DoTimer_SpellLocalization["Rugido Desmoralizador"] = "Demoralizing Roar"
    DoTimer_SpellLocalization["Hibernar"] = "Hibernate"
    DoTimer_SpellLocalization["Enredar"] = "Entangling Roots"
    DoTimer_SpellLocalization["Fuego Lunar"] = "Moonfire"
    DoTimer_SpellLocalization["Picadura de Insecto"] = "Insect Swarm"
    DoTimer_SpellLocalization["Rejuvenecimiento"] = "Rejuvenation"
    DoTimer_SpellLocalization["Recrecimiento"] = "Regrowth"
    DoTimer_SpellLocalization["Tranquilidad"] = "Tranquility"
    
    -- HUNTER
    DoTimer_SpellLocalization["Picadura de Serpiente"] = "Serpent Sting"
    DoTimer_SpellLocalization["Picadura de Víbora"] = "Viper Sting"
    DoTimer_SpellLocalization["Picadura de Escorpión"] = "Scorpid Sting"
    DoTimer_SpellLocalization["Marca del Cazador"] = "Hunter's Mark"
    DoTimer_SpellLocalization["Trampa de Hielo"] = "Freezing Trap"
    DoTimer_SpellLocalization["Trampa de Inmovilización"] = "Immolation Trap"
    DoTimer_SpellLocalization["Trampa Explosiva"] = "Explosive Trap"
    DoTimer_SpellLocalization["Amedrentar"] = "Scare Beast"
    DoTimer_SpellLocalization["Conmoción"] = "Concussive Shot"
    DoTimer_SpellLocalization["Aturdir"] = "Wyvern Sting"
    
    -- MAGE
    DoTimer_SpellLocalization["Polimorfia"] = "Polymorph"
    DoTimer_SpellLocalization["Ralentizar"] = "Slow"
    DoTimer_SpellLocalization["Nova de Escarcha"] = "Frost Nova"
    DoTimer_SpellLocalization["Armadura de Hielo"] = "Ice Armor"
    DoTimer_SpellLocalization["Armadura de Escarcha"] = "Frost Armor"
    DoTimer_SpellLocalization["Armadura de Mago"] = "Mage Armor"
    DoTimer_SpellLocalization["Barrera de Hielo"] = "Ice Barrier"
    DoTimer_SpellLocalization["Contrahechizo"] = "Counterspell"
    DoTimer_SpellLocalization["Quemadura"] = "Scorch"
    DoTimer_SpellLocalization["Ignición"] = "Ignite"
    
    -- ROGUE
    DoTimer_SpellLocalization["Hemorragia"] = "Hemorrhage"
    DoTimer_SpellLocalization["Ruptura"] = "Rupture"
    DoTimer_SpellLocalization["Destripamiento"] = "Garrote"
    DoTimer_SpellLocalization["Golpe Bajo"] = "Cheap Shot"
    DoTimer_SpellLocalization["Golpe en los Riñones"] = "Kidney Shot"
    DoTimer_SpellLocalization["Cegar"] = "Blind"
    DoTimer_SpellLocalization["Estrangular"] = "Gouge"
    DoTimer_SpellLocalization["Veneno Mortal"] = "Deadly Poison"
    DoTimer_SpellLocalization["Veneno Paralizante"] = "Crippling Poison"
    DoTimer_SpellLocalization["Veneno de Mente"] = "Mind-numbing Poison"
    DoTimer_SpellLocalization["Veneno de Heridas"] = "Wound Poison"
    DoTimer_SpellLocalization["Exponer Armadura"] = "Expose Armor"
    
    -- SHAMAN
    DoTimer_SpellLocalization["Descarga de Llamas"] = "Flame Shock"
    DoTimer_SpellLocalization["Descarga de Escarcha"] = "Frost Shock"
    DoTimer_SpellLocalization["Descarga de Tierra"] = "Earth Shock"
    DoTimer_SpellLocalization["Escudo de Relámpagos"] = "Lightning Shield"
    DoTimer_SpellLocalization["Escudo de Agua"] = "Water Shield"
    DoTimer_SpellLocalization["Escudo de Tierra"] = "Earth Shield"
    DoTimer_SpellLocalization["Arma de Lenguas de Fuego"] = "Flametongue Weapon"
    DoTimer_SpellLocalization["Arma de Viento Furioso"] = "Windfury Weapon"
    DoTimer_SpellLocalization["Arma de Piedra de Roca"] = "Rockbiter Weapon"
    DoTimer_SpellLocalization["Arma de Lengua de Escarcha"] = "Frostbrand Weapon"
end

-- Nota: La función DoTimer_NormalizeSpellName está definida en DoTimer_Patch.lua
